import Navbar from '../components/Navbar'


export const metadata = {
    title: 'Electronics Items',
    description: 'Generated by surendar',
}


const ElectronicsLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <div>
            <Navbar />
            {children}
        </div>
    );
}

export default ElectronicsLayout;