import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from "./components/Navbar"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Surendar Sl',
  description: 'Generated by surendar',
}


export default function RootLayout({
  children,
  newUserName,
}: {
  children: React.ReactNode
  newUserName: string;
}) {
  console.log("User Name (in RootLayout):", newUserName);
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navbar newUserName={newUserName} />
        {children}
        </body>
    </html>
  )
}

