import ShopNav from '../components/ShopNav'

export const metadata = {
    title: 'Shopping Page',
    description: 'Generated by surendar',
}


const ShopLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <div>
            <ShopNav />
            {children}
        </div>
    );
}

export default ShopLayout;